create table "public"."crosswordpuzzle" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "date" date not null
);


alter table "public"."crosswordpuzzle" enable row level security;

create table "public"."crosswordsolves" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" bigint,
    "puzzle_id" bigint,
    "is_solved" boolean
);


alter table "public"."crosswordsolves" enable row level security;

create table "public"."crosswordusers" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "cookie" text not null,
    "username" text not null
);


alter table "public"."crosswordusers" enable row level security;


CREATE UNIQUE INDEX crosswordpuzzle_pkey ON public.crosswordpuzzle USING btree (id);

CREATE UNIQUE INDEX crosswordsolves_pkey ON public.crosswordsolves USING btree (id);

CREATE UNIQUE INDEX crosswordusers_pkey ON public.crosswordusers USING btree (id);


alter table "public"."crosswordpuzzle" add constraint "crosswordpuzzle_pkey" PRIMARY KEY using index "crosswordpuzzle_pkey";

alter table "public"."crosswordsolves" add constraint "crosswordsolves_pkey" PRIMARY KEY using index "crosswordsolves_pkey";

alter table "public"."crosswordusers" add constraint "crosswordusers_pkey" PRIMARY KEY using index "crosswordusers_pkey";

alter table "public"."crosswordsolves" add constraint "crosswordsolves_puzzle_id_fkey" FOREIGN KEY (puzzle_id) REFERENCES crosswordpuzzle(id) not valid;

alter table "public"."crosswordsolves" validate constraint "crosswordsolves_puzzle_id_fkey";

alter table "public"."crosswordsolves" add constraint "crosswordsolves_user_id_fkey" FOREIGN KEY (user_id) REFERENCES crosswordusers(id) not valid;

alter table "public"."crosswordsolves" validate constraint "crosswordsolves_user_id_fkey";
