alter table "public"."crosswordsolves" drop constraint "crosswordsolves_puzzle_id_fkey";

alter table "public"."crosswordpuzzle" drop constraint "crosswordpuzzle_pkey";

drop index if exists "public"."crosswordpuzzle_pkey";

drop table "public"."crosswordpuzzle";

create table "public"."crosswordpuzzles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "date" date not null
);


alter table "public"."crosswordpuzzles" enable row level security;

CREATE UNIQUE INDEX crosswordpuzzle_pkey ON public.crosswordpuzzles USING btree (id);

alter table "public"."crosswordpuzzles" add constraint "crosswordpuzzle_pkey" PRIMARY KEY using index "crosswordpuzzle_pkey";

alter table "public"."crosswordsolves" add constraint "crosswordsolves_puzzle_id_fkey" FOREIGN KEY (puzzle_id) REFERENCES crosswordpuzzles(id) not valid;

alter table "public"."crosswordsolves" validate constraint "crosswordsolves_puzzle_id_fkey";